### ISSUE TITLE
Node crashed while changing password.

### ISSUE THREAD

**Issue by HellerCommaA** [SpiderOak/Encryptr#242]
Node crashed while changing password from a complex (20+ character password) to a 10+ character password. OSX 10.11.1

`Uncaught node.js Error 

TypeError: Cannot read property 'toJSON' of undefined
    at changePassphraseCallback (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/Encryptr.js:2218:72)
    at file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:822:9
    at Request.callback (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:7741:3)
    at Request.<anonymous> (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:7466:10)
    at Request.Emitter.emit (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:6952:20)
    at XMLHttpRequest.xhr.onreadystatechange (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:7811:10)`

**Comment by daviddahl** [comment]
I just tried to reproduce, but was unable to. Is this with Encryptr 2.0? Were you able to re-login?

**Comment by HellerCommaA** [comment]
Yes, it looks like the password was actually reset. I'm on 2.0.0.  ...Not entirely sure what happened to be honest. I also just attempted to reproduce and wasn't able to.  Will close the issue.

**Comment by daviddahl** [comment]
Ok, feel free to re-open if it happens again. I am curious what commit of Crypton @devgeeks is using in this 2.0.0 build

**Comment by devgeeks** [comment]
I don't think it's a Crypton issue... the `toJSON` seems backbone related...

@HellerCommaA - Make sure to reopen if it happens again :/

**Comment by HellerCommaA** [comment]
Will do.  Wish I had more info to give you guys. Sorry :cry:
