### ISSUE TITLE
Uncaught node.js error when changing passphrase

### ISSUE THREAD

**Issue by c633** [SpiderOak/Encryptr#273]
I got this error when changing my passphrase

```
Uncaught node.js Error 

TypeError: Cannot read property 'toJSON' of undefined
    at changePassphraseCallback (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/Encryptr.js:2218:72)
    at file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:822:9
    at Request.callback (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:7741:3)
    at Request.<anonymous> (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:7466:10)
    at Request.Emitter.emit (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:6952:20)
    at XMLHttpRequest.xhr.onreadystatechange (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:7811:10)
```

**Comment by devgeeks** [comment]
@c633 did your passphrase successfully change? Or stay the old passphrase?

Can you try again and see if it's a transient error?

**Comment by c633** [comment]
It successfully changed and this error happened in the first time I change my passphrase only.

**Comment by devgeeks** [comment]
Thanks for that, I'll look into it.
