### ISSUE TITLE
Uncaught node.js Error

### ISSUE THREAD

**Issue by sudomake** [SpiderOak/Encryptr#288]
## System
OSX 10.12.5
Encryptr 2.0.0

## What I was trying to do
Delete an account entry in Encryptr.  I clicked on the entry.  I clicked on the trash can icon.  Encryptr brought me back to the login screen.  I logged back in.

## Error message
```
Uncaught node.js Error 

TypeError: Cannot read property 'fetch' of undefined
    at file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/Encryptr.js:1539:33
    at file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:1703:11
    at file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:2225:7
    at Request.callback (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:7741:3)
    at Request.<anonymous> (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:7466:10)
    at Request.Emitter.emit (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:6952:20)
    at XMLHttpRequest.xhr.onreadystatechange (file:///Applications/Encryptr.app/Contents/Resources/app.nw/js/crypton.js:7811:10)
```

**Comment by bernardofd** [comment]
The same thing happened to me, but on Linux. The same error message doing the same (deleting an entry).

## System

Manjaro Gnome (Arch): `uname -a: Linux 4.9.78-1-MANJARO #1 SMP PREEMPT Wed Jan 24 12:59:31 UTC 2018 x86_64 GNU/Linux`
Encryptr 2.0.0 (from [AUR](https://aur.archlinux.org/packages/encryptr/))

**Update**: The entry was successfully deleted, but I had to restart the app to use it again.
